In [1]:
#PIL pour ouvrir l'image, matplotlib l'export et numpy le traitment
from PIL import Image
from matplotlib import pyplot as plt
import numpy as np

#-----------------------------------------------------------------#
#                                                                 #
#   fait par Roamin Blondel                                       # 
#   1M8, Gymnase Auguste Piccard, mars 2022                       #
#                                                                 #
#-----------------------------------------------------------------#
#-----------------------------------------------------------------
#-----------------------------------------------------------------
#
#   ce programme prend une image en entrée et en sort l'image plus
#   petite selon une résolution donnée (ainsi que la liste des valeurs
#   RGB des différents pixels)
#
#-----------------------------------------------------------------

#calcul de la nouvelle résolution optimale selon celle entrée
def calcRes(n_res, n_resmin, i_l, i_h):
    #la calcul se fait par itération en maximisant certains facteurs
    #
    #initialisation de l'essai de résolution
    n_dim = [1,1]

    #initialisation des variables pour les boucles
    #l'une de variables par du plus grand coté possible, l'autre du plus petit
    i = n_res
    j = 1
    #on parcours les différentes valeurs afin de trouver celles optimales
    while i >= 1:
        while j <= n_res/i:
            #on vérifie 2 conditions pour maximiser le ratio de la nouvelle image
            #
            #condition 1 : la différence entre le ratio de l'image de taille normale
            #   et des nouvelles valeurs doit être plus petite qu'avec les anciennes valeurs
            #condition 2 : le nombre de pixels de la nouvelle image doit être plus grand qu'une
            #   résolution minimale
            if np.abs(i/j-i_h/i_l) < np.abs(n_dim[0]/n_dim[1]-i_h/i_l) and i*j > n_resmin:
                #si les deux conditions sont remplies, on applique les nouvelles valeurs
                n_dim[0] = i
                n_dim[1] = j

            j += 1

        j = 1
        i -= 1

    return n_dim

#calcul de la couleur de l'image réduite
def redIm(arr, n_l, n_h):
    #initialisation de la nouvelle image ; attribution de dtype pour éviter les bugs
    n_arr = np.zeros((n_h,n_l,3),dtype=np.uint8)

    #moyenne par carré de la grande image pour retourner celle réduite
    #en parcourant chaque pixels de la nouvelle image
    for i in range(n_h):
        for j in range(n_l):
            #initialisation de liste de valeurs RGB dans l#image originale
            i_red = []
            i_green = []
            i_blue = []

            #variable de la hauteur et longeurs à parcourir pour faire la moyenne
            #des pixels de l'image originale correspondant au pixel de la petite parcourue
            d_h = int(np.round(len(arr)/n_h))-1
            d_l = int(np.round(len(arr[0])/n_l))-1
            #parcours des "mégapixels" et enregistrement de valeurs RGB dans les listes faite plus haut
            for k in range(d_h):
                for l in range(d_l):
                    i_red.append(arr[i*d_h+k][j*d_l+l][0])
                    i_green.append(arr[i*d_h+k][j*d_l+l][1])
                    i_blue.append(arr[i*d_h+k][j*d_l+l][2])

            #moyenne de chaque liste pour faire les valeurs des nouveaux pixels
            f_r = np.mean(i_red)
            f_g = np.mean(i_green)
            f_b = np.mean(i_blue)
            #ajout des valeurs à l'image
            n_arr[i][j]=[f_r,f_g,f_b]

    return n_arr

#opération compléte pour pixeliser
def pixelise(image, new_res):
    #ouverture de l'image et conversion en liste RGB
    i_img = Image.open(image)
    i_arr = np.array(i_img)

    #calcul de la nouvelle résolution
    n_dim = calcRes(new_res,new_res*0.8,len(i_arr[0]),len(i_arr))
    #calcul de l'image réduite
    red_im = redIm(i_arr,n_dim[1],n_dim[0])

    return red_im

#récupération du fichier et de la nouvelle résolution ; impression de la nouvelle image
#
#initialisation de la "color map"
cmap = plt.cm.jet
#interaction dans la console
def new_image():
    #demande des nom de fichier (formats testé : .png, .jpg) et de la résolution
    i_image = input('Type the file name : ')
    new_res = input('Type the new resolution : ')

    #calcul de l'image et impression de la liste dans la console
    output = pixelise('{}'.format(i_image), int(new_res))
    print(output)
    #enregistrement de l'image réduite ; le format peut être modifié en n'importe lequel supporté
    #   (testé avec .png et .bmp)
    plt.imsave('{}-small.png'.format(i_image[:-4]), output, cmap=cmap)


#exécution
new_image()

Type the file name :  trou noir.png
Type the new resolution :  250
[[[  1  35  44]
  [  3  38  43]
  [ 10  29  29]
  [ 21  29  25]
  [ 32  32  25]
  [ 42  35  25]
  [ 51  37  23]
  [ 62  41  24]
  [ 65  41  21]
  [ 67  41  21]
  [ 60  38  21]
  [ 50  34  21]
  [ 38  31  20]
  [ 29  32  23]
  [ 20  33  27]
  [  6  39  36]
  [  0  45  45]
  [  0  42  43]
  [  0  37  40]]

 [[  7  38  42]
  [ 16  32  32]
  [ 25  28  24]
  [ 37  31  22]
  [ 55  37  24]
  [ 67  42  25]
  [ 95  52  27]
  [124  64  30]
  [144  75  33]
  [136  71  30]
  [111  59  24]
  [ 80  43  19]
  [ 58  33  17]
  [ 40  29  17]
  [ 32  32  23]
  [ 19  32  27]
  [  5  39  38]
  [  0  43  43]
  [  0  41  42]]

 [[ 23  38  37]
  [ 32  34  29]
  [ 37  30  22]
  [ 62  37  24]
  [ 86  45  26]
  [131  65  36]
  [184 108  65]
  [219 145  94]
  [231 165 113]
  [225 153 107]
  [183 104  62]
  [129  62  27]
  [ 88  42  17]
  [ 58  32  16]
  [ 43  31  20]
  [ 30  32  24]
  [ 15  32  29]
  [  1  38  38]
  [  0  41  43]]

 [[ 36  38  33]

In [8]:
#-----------------------------------------------------------------
#
#ce programme rend un image à partir d'une liste 
#   RGB, niveau de gris ou noir et blanc
#
#-----------------------------------------------------------------

#fonction d'analyse du type d'image
#   et de mise en forme de la liste
def im_type(im):
    #1er verification : est-ce déjà une liste RGB
    if type(im[0][0]) == 'list':
        #convertit la liste en liste numpy afin d'éviter des problémes
        return np.array(im, dtype='uint8')
    else:
        #teste si l'image est en niveau de gris
        #
        #initialisation de la valeur teste
        is_grayscale = False
        #parcours des éléments de la liste
        for i in range(len(im)):
            for j in range(len(im[0])):
                #si l'une des valeurs n'est pas 0 ou 1, c'est en niveau de gris
                if im[i][j] != 0 and im[i][j] != 1:
                    is_grayscale = True
        
        #initialisation de la liste de l'image rendue
        n_arr = np.zeros((len(im),len(im[0]),3),dtype=np.uint8)
        #attribut des différentes valeurs pour convertir en RGB
        # si c'est en niveau de gris ou noir et blanc
        if is_grayscale:
            #parcours des elements de la liste originale
            # et implémentations dans la nouvelle liste
            for i in range(len(im)):
                for j in range(len(im[0])):
                    #la valeur est mise dans chaque cannaux pour avoir
                    #   la liste finale en niveau de gris
                    n_arr[i][j] = [im[i][j], im[i][j], im[i][j]]
        else:
            #parcours des elements de la liste originale
            # et implémentations dans la nouvelle liste
            for i in range(len(im)):
                for j in range(len(im[0])):
                    #si la valeur vaut 0, la valeur est mise sur blanc
                    # sinon sur noir
                    if im[i][j] == 0:
                        n_arr[i][j] = [255,255,255]
                    elif im[i][j] == 1:
                        n_arr[i][j] = [0,0,0]
        
        return n_arr


#-----------------------------------------------------------------
#-----------------------------------------------------------------
#   tableau d'entrée
#-----------------------------------------------------------------
#-----------------------------------------------------------------
#   RGB
#image = [[[255,255,255],[0,0,0],[255,255,255],[0,0,0],[255,255,255]],
#         [[255,255,255],[0,0,0],[255,255,255],[0,0,0],[255,255,255]],
#         [[255,255,255],[255,255,255],[255,255,255],[255,255,255],[255,255,255]],
#         [[0,0,0],[255,255,255],[255,255,255],[255,255,255],[0,0,0]],
#         [[255,255,255],[0,0,0],[0,0,0],[0,0,0],[255,255,255]]]
#
#   Grayscale
#image = [[255,0,255,0,255],
#         [255,0,255,0,255],
#         [255,255,255,255,255],
#         [0,255,255,255,0],
#         [255,0,0,0,255]]
#
#   Black and White
image = [[0,1,0,1,0],
         [0,1,0,1,0],
         [0,0,0,0,0],
         [1,0,0,0,1],
         [0,1,1,1,0]]

#traitement de la liste d'entrée
image_to_proceed = im_type(image)
#impression de la liste
print(image_to_proceed)

#rendu de l'image
def render_image():
    #demande du nom de sauvegarde
    name = input('Save name : ')
    #enregistrement de l'image ; le format peut être modifié en n'importe lequel supporté
    #   (testé avec .png et .bmp)
    plt.imsave('{}.png'.format(name), image_to_proceed, cmap=cmap)

#exécution
render_image()

[[[255 255 255]
  [  0   0   0]
  [255 255 255]
  [  0   0   0]
  [255 255 255]]

 [[255 255 255]
  [  0   0   0]
  [255 255 255]
  [  0   0   0]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0   0]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [  0   0   0]]

 [[255 255 255]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [255 255 255]]]
Save name :  smiley
